<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="8" passed="3" failed="2" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-03T14:36:41 EDT" name="Suite" finished-at="2021-06-03T14:36:41 EDT" duration-ms="225">
    <groups>
      <group name="Sanity">
        <method signature="GroupDemo1.test3()[pri:3, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test3" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo1.test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test4" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo2.test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" name="test4" class="com.testNGListenerDemo.GroupDemo2"/>
      </group> <!-- Sanity -->
      <group name="windows.Sanity">
        <method signature="GroupDemo1.test1()[pri:1, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test1" class="com.testNGListenerDemo.GroupDemo1"/>
      </group> <!-- windows.Sanity -->
      <group name="Regression">
        <method signature="GroupDemo1.test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test2" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo1.test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test4" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo2.test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" name="test4" class="com.testNGListenerDemo.GroupDemo2"/>
        <method signature="GroupDemo2.test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" name="test2" class="com.testNGListenerDemo.GroupDemo2"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="GroupDemo1.test1()[pri:1, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test1" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo1.test3()[pri:3, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" name="test3" class="com.testNGListenerDemo.GroupDemo1"/>
        <method signature="GroupDemo2.test1()[pri:1, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" name="test1" class="com.testNGListenerDemo.GroupDemo2"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2021-06-03T14:36:41 EDT" name="group-demo-1" finished-at="2021-06-03T14:36:41 EDT" duration-ms="94">
      <class name="com.testNGListenerDemo.GroupDemo1">
        <test-method signature="test1()[pri:1, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" started-at="2021-06-03T14:36:41 EDT" name="test1" finished-at="2021-06-03T14:36:41 EDT" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" started-at="2021-06-03T14:36:41 EDT" name="test2" finished-at="2021-06-03T14:36:41 EDT" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.testNGListenerDemo.GroupDemo1.test2(GroupDemo1.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test3()[pri:3, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" started-at="2021-06-03T14:36:41 EDT" name="test3" finished-at="2021-06-03T14:36:41 EDT" depends-on-methods="com.testNGListenerDemo.GroupDemo1.test2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method GroupDemo1.test3()[pri:3, instance:com.testNGListenerDemo.GroupDemo1@64e7619d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method GroupDemo1.test3()[pri:3, instance:com.testNGListenerDemo.GroupDemo1@64e7619d] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:97)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method signature="test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo1@64e7619d]" started-at="2021-06-03T14:36:41 EDT" name="test4" finished-at="2021-06-03T14:36:41 EDT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
      </class> <!-- com.testNGListenerDemo.GroupDemo1 -->
    </test> <!-- group-demo-1 -->
    <test started-at="2021-06-03T14:36:41 EDT" name="group-demo-2" finished-at="2021-06-03T14:36:41 EDT" duration-ms="32">
      <class name="com.testNGListenerDemo.GroupDemo2">
        <test-method signature="test1()[pri:1, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" started-at="2021-06-03T14:36:41 EDT" name="test1" finished-at="2021-06-03T14:36:41 EDT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test4()[pri:4, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" started-at="2021-06-03T14:36:41 EDT" name="test4" finished-at="2021-06-03T14:36:41 EDT" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.testNGListenerDemo.GroupDemo2.test4(GroupDemo2.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae]" started-at="2021-06-03T14:36:41 EDT" name="test2" finished-at="2021-06-03T14:36:41 EDT" depends-on-methods="com.testNGListenerDemo.GroupDemo2.test4" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method GroupDemo2.test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method GroupDemo2.test2()[pri:2, instance:com.testNGListenerDemo.GroupDemo2@24c4ddae] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:97)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.testNGListenerDemo.GroupDemo2 -->
    </test> <!-- group-demo-2 -->
  </suite> <!-- Suite -->
</testng-results>
